{% set name = "conda-recipe-manager" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/conda-recipe-manager/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bae9b94a2e6fdba26c497bbecd94afcd554a0e71087d24e2659ded212f376168

build:
  number: 0 # trigger
  script: pip install . --no-deps --no-build-isolation -vv
  noarch: python
  entry_points:
    - conda-recipe-manager = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager
    - crm = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11
    - click >=8.1.7
    - conda
    - jinja2
    - pyyaml
    - jsonschema
    - requests
    - gitpython
    - networkx
    - matplotlib-base
    - pygraphviz

test:
  imports:
    - conda_recipe_manager.commands
    - conda_recipe_manager.licenses
    - conda_recipe_manager.parser
  source_files:
    - tests/
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pyfakefs
    - git  # Required for `gitpython` tests
  commands:
    - pip check
    - python -m pytest -n auto --ignore=tests/test_aux_files tests/

about:
  home: https://github.com/anaconda/conda-recipe-manager
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/anaconda/conda-recipe-manager/blob/main/LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://conda-incubator.github.io/conda-recipe-manager/index.html
  dev_url: https://github.com/anaconda/conda-recipe-manager

extra:
  recipe-maintainers:
    - schuylermartin45
    - beeankha
