{% set name = "conda-recipe-manager" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 12a3b6f0aa75a7217bff70121d7521c8944579ccc3f902657f6c07acc73ee4f6

build:
  number: 1
  noarch: python
  script: {{PYTHON}} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - conda-recipe-manager = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager
    - crm = conda_recipe_manager.commands.conda_recipe_manager:conda_recipe_manager

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11
    - click >=8.1.7,<8.2.0
    - conda
    - jinja2
    - pyyaml
    - jsonschema
    - requests
    - gitpython
    - networkx
    - matplotlib-base
    - pygraphviz

test:
  imports:
    - conda_recipe_manager.commands
    - conda_recipe_manager.fetcher
    - conda_recipe_manager.grapher
    - conda_recipe_manager.licenses
    - conda_recipe_manager.parser
    - conda_recipe_manager.scanner
    - conda_recipe_manager.utils
  source_files:
    - tests/
    - recipe/meta.yaml
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pyfakefs
    - git  # Required for `gitpython` tests
    - yq
  commands:
    - pip check
    - conda-recipe-manager --help
    - crm --help
    - crm bump-recipe --help
    - crm convert --help
    # Test the crm convert usage
    - crm convert recipe/meta.yaml | [[ $(yq ".context.name") == '"conda-recipe-manager"' ]]  # [unix]
    - crm graph --help
    - crm patch --help
    - crm rattler-bulk-build --help
    - python -m pytest -n auto --ignore=tests/test_aux_files tests/

about:
  home: https://github.com/conda/conda-recipe-manager
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://conda.github.io/conda-recipe-manager/index.html
  dev_url: https://github.com/conda/conda-recipe-manager

extra:
  skip-lints:
    - avoid_noarch
  recipe-maintainers:
    - schuylermartin45
